openapi: 3.0.0
info:
  version: 1.0.0
  title: API
  description: ""
externalDocs:
  description: More info
  url: https://changeme.com
paths:
  /my_service/my_entity:
    get:
      summary: List
      description: Get a list
      operationId: list_my_entities
      parameters:
        - name: current_user_id
          description: The ID of the currently authenticated user.
          in: header
          schema:
            type: string
            format: uuid
            example: 61200625-2463-4b27-babd-f478198a0638
      tags:
        - MyEntity
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/MyService.MyEntity"
components:
  schemas:
    Entity:
      allOf:
        - allOf:
            - type: object
              properties:
                attributes:
                  type: object
                  properties:
                    created_at:
                      description: UTC timestamp when entity was created in the database. Set by
                        server.
                      type: string
                      format: date-time
                    updated_at:
                      description: UTC timestamp when entity was updated in the database. Set by
                        server.
                      type: string
                      format: date-time
            - type: object
              required:
                - id
                - type
              properties:
                id:
                  type: string
                  format: uuid
                type:
                  type: string
                relationships:
                  type: object
                  properties: null
    MyService.MyEntity:
      allOf:
        - $ref: "#/components/schemas/Entity"
        - properties:
            type:
              enum:
                - MyService.MyEntity
        - properties:
            attributes:
              properties:
                name:
                  type: string
            relationships:
              properties:
                my_other_entities:
                  allOf:
                    - type: object
                      required:
                        - data
                      properties:
                        data:
                          type: array
                          items:
                            type: object
                            required:
                              - id
                              - type
                            properties:
                              id:
                                type: string
                                format: uuid
                              type:
                                type: string
                    - properties:
                        data:
                          items:
                            properties:
                              type:
                                enum:
                                  - MyService.MyEntity
